### PR TITLE
Fixes #109 Implements multipart message fix and cancellation of file download.

### LINKED ISSUE #109: DomainFileStore fixes
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A SDK issue that is related to  [IME issue #393](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/393).
Contains fixes for Download cancellation([IME #393](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/393)) and multipart messages ([Webservice #117](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/117) and [Integration tests #16](https://github.com/RHEAGROUP/ecss-10-25-annexc-integration-tests/issues/16))

### PR DESCRIPTION
**Pull request by lxatrhea**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Cancellation support for file download (ReadFilemethod in Session and DAL).
Support for multipart HTML response messages.

### CODE REVIEW

File: CDP4Dal/Session.cs [hunk 1]
```diff
@@ -686,12 +691,26 @@ public async Task Reload()
             }
         }
 
+        /// <summary>
+        /// Can a Cancel action be executed?
+        /// </summary>
+        /// <returns>True is Cancel is allowed, otherwise false.</returns>
+        public bool CanCancel()
+        {
+            if (this.cancellationTokenSource == null)
```
Comment (samatrhea) [inline CDP4Dal/Session.cs:700]: the session object is multi-threaded... so, this may become a problem i think. Which read/write is being cancelled?

File: CDP4ServicesDal/CdpServicesDal.cs [hunk 2]
```diff
@@ -733,17 +712,48 @@ private void ProcessHeaders(HttpResponseMessage httpResponseMessage)
...
         }
-        
+
+        /// <summary>
+        /// Checks message content header for CDP4 tags an compatiple content-types
+        /// </summary>
+        /// <param name="headerString">The header <see cref="string"/></param>
+        /// <param name="allowMultiPart">Indication if multipart Content-Type is allowed</param>
+        /// <returns></returns>
+        private bool IsCDP4ContentType(string headerString, bool allowMultiPart)
```
Comment (samatrhea) [inline CDP4ServicesDal/CdpServicesDal.cs:735]: this we need to talk about... i propose we do a skype call
