### PR TITLE
Fix type comparison in OrderedItemList

### LINKED ISSUE #82: Incorrect type check for Thing in SDK OrderedItemList
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
At https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/fce21a2b9bed488be13eac2533f301653a84a9ff/CDP4Common/Types/OrderedItemList.cs#L566

In `OrderedItemList.Add(...)` the comparison `if (typeof(T) == typeof(Thing))` is incorrect because it only checks that the type of the incoming `item` is directly a `Thing`, not one of its subtypes.

The correct condition is `if (item is Thing)` which properly checks that the `item` is a `Thing` or any of its subtypes. Alternatively `typeof(T).IsSubclassOf(typeof(Thing))` can be used, if you are sure `T` cannot be `Thing` but must be one of its subtypes.

### Steps to Reproduce
None, found by code inspection.

### System Configuration
Any code that uses the C# SDK.

  - CDP4 version: 
  - [x] CDP4Common: development branch     
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information: Please check for other possible occurrences of the same condition.

### PR DESCRIPTION
**Pull request by IevhenIkonnykov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-SDK-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Closes #82

### CODE REVIEW

**Comment by samatrhea** [comment]
in the issue i added a comment to look at how the whole class can be cleaned-up. This fix is so "minimal" it seems that request has not been taken into account. Does that mean the class needs no further improvement?

**Comment by IevhenIkonnykov** [comment]
I beg your pardon. My fault, I concentrated on the description of the issue and did not notice a comment. I will work through it a little bit later.

File: CDP4Common/Types/OrderedItemList.cs [hunk 1]
```diff
@@ -574,5 +539,61 @@ private void Add(long sortKey, T item)
...
+        /// </param>
+        /// <exception cref="ArgumentOutOfRangeException">
+        /// Thrown when <see paramref="index"/> is out of the allowed range.
+        /// </exception>
+        private void ValidateIndex(int index)
+        {
+            if (index < 0 || index >= this.sortedItems.Count)
+            {
+                throw new ArgumentOutOfRangeException(
+                    "index", string.Format("The index {0} does not exist in the ordered item list, valid range is 0 to {1}", index, this.sortedItems.Count - 1));
```
Comment (samatrhea) [inline CDP4Common/Types/OrderedItemList.cs]: please make use of string interpolation **$** syntax instead of **string.format**

File: CDP4Common/Types/OrderedItemList.cs [hunk 2]
```diff
@@ -574,5 +539,61 @@ private void Add(long sortKey, T item)
...
+        /// </param>
+        /// <exception cref="InvalidOperationException">
+        /// Thrown when <see paramref="item"/> is already in the list.
+        /// </exception>
+        private void ValidateItemForExistence(T item)
+        {
+            if (this.sortedItems.Values.Contains(item))
+            {
+                var thing = item as Thing;
+                throw new InvalidOperationException(string.Format("The sorted list already contains the item {0}", thing != null ? thing.Iid.ToString() : "An item is not a Thing. Incorrect use of validation."));
```
Comment (samatrhea) [inline CDP4Common/Types/OrderedItemList.cs]: please make use of string interpolation **$** syntax instead of **string.format**

Since the class is called OrderedItemList I propose that in the exception message we replace **sorted** with **ordered**

File: CDP4Common/Types/OrderedItemList.cs (hunk 1 above)
Comment (lxatrhea) [reply CDP4Common/Types/OrderedItemList.cs]: If SortedItems doesn't contain any items, then the error states "valid range is 0 to -1".

File: CDP4Common/Types/OrderedItemList.cs [hunk 3]
```diff
@@ -574,5 +539,61 @@ private void Add(long sortKey, T item)
...
+        /// <param name="value">
+        /// The value to validate.
+        /// </param>
+        /// <param name="message">
+        /// The message to pass to an exception if validation not passes.
+        /// </param>
+        /// <exception cref="ArgumentNullException">
+        /// Thrown when <see paramref="value"/> is null.
+        /// </exception>
+        private void ValidateValueForNull(object value, string message = "")
```
Comment (lxatrhea) [inline CDP4Common/Types/OrderedItemList.cs]: If you make the default value for message "An item cannot be null", you can remove it from 3 other places and it will be easier to reuse it for future changes.
